config/routes.rb
Kabuderby::Application.routes.draw do
  get "toppage/index"
  match'/signin', to:'sessions#new', via:'get'
  match'/signout', to:'sessions#destroy',via:'delete'
  root  'about#index'
  match '/about', to:'about#index', via:'get'
  get "/tutorial/select"
  get "/tutorial/buy/:id", to: "tutorial#buy", as: 'tutorial_buy'
  post "/tutorial/confirm/:id", to: "tutorial#confirm", as: 'tutorial_confirm'
  post "/tutorial/complete/:id", to: "tutorial#complete", as: 'tutorial_complete'
  get "toppage/mypage"
  get "/tutorial/select_sell"
  get "/tutorial/sell/:id", to: "tutorial#sell", as: 'tutorial_sell'
  post "/tutorial/sell_confirm/:id", to: "tutorial#sell_confirm", as: 'tutorial_sell_confirm'
  post "/tutorial/sell_complete/:id", to: "tutorial#sell_complete", as: 'tutorial_sell_complete'
  get "/toppage/rank"
  get "/toppage/order"
  get "/toppage/lesson"
  get "/trial/select"
  get "/trial/buy/:id", to: "trial#buy", as: 'trial_buy'
  post "/trial/confirm/:id", to: "trial#confirm", as: 'trial_confirm'
  post "/trial/complete/:id", to: "trial#complete", as: 'trial_complete'
  get "/trial/select_sell/:id", to: "trial#select_sell", as: 'trial_select_sell'
  get "/trial/sell/:id", to: "trial#sell", as: 'trial_sell'
  post "/trial/sell_confirm/:id", to: "trial#sell_confirm", as: 'trial_sell_confirm'
  post "/trial/sell_complete/:id", to: "trial#sell_complete", as: 'trial_sell_complete'
  get "/trial/order/:id", to: "trial#order", as: 'trial_order'
  get "/about/sample"



  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/controllers/trial_controller.rb
class TrialController < ApplicationController
	before_action :set_company, only: [:buy, :confirm, :complete, :select_sell, :sell, :sell_confirm, :sell_complete, :order]
	before_action :set_user,only: [:select, :buy, :confirm, :complete]
	def select
		@companies = Company.all
	end
	def buy
		@order = Order.new(company_id: params[:id], order_value: @company.value)
		@portfolio = Portfolio.new(company_id: params[:id], )
	end
	def confirm
		@order = Order.new(company_id: params[:id], order_value: @company.value, quantity: params[:order][:quantity], user_id: @user.id)
		if params[:order][:quantity].to_i % 100 != 0
			@error_message = 'error'
			render 'buy'
		end
	end
	def complete

	end
	def select_sell
	end
	def sell
		@order = Order.new(company_id: params[:id], order_value: @company.value)
	end
	def sell_confirm
		@order = Order.new(company_id: params[:id], order_value: @company.value)
	end
	def sell_complete
	end
	def order
	end

	private
	def set_company 
      #params[id]に/users/数でとってきた値を入れている
      @company = Company.find(params[:id])
    end
    def set_user
    	@user = User.find_by(id: 1)
    end

end

app/helpers/trial_helper.rb
module TrialHelper
end

app/views/trial/buy.html.erb
<% if @error_message %>
	<div class="alert alert-warning"><%= @error_message %></div>
<% end %>
<h1>チュートリアル購入ページ</h1>
この画面では数量を入力します。
<h2>残高:<%= @user.cash %>円</h2>
<h2>銘柄: <%= @company.name %></h2>
<h2>株価:  <%= @company.value %>円</h2>
<h2>単元株: <%= @company.unit %></h2>
<%= form_for @order, url: trial_confirm_path do |f| %>
    <div class="field">
    <%= f.label :quantity, "購入株数" %><br>
    <%= f.text_field :quantity %>
    <%= f.hidden_field :company_id %>
    <%= f.hidden_field :order_value %>
    購入株数に100を入力してみましょう！
    </div>
    <%= f.submit "確認画面へ", class: "btn btn-large btn-primary" %>
<% end %>

app/views/trial/complete.html.erb
<h1>チュートリアル購入完了</h1>
購入完了しました。<br>
次は今買った株を売ってみましょう！
<h1><%= link_to 'チュートリアル売却へ', trial_select_sell_path %></h1>

app/views/trial/confirm.html.erb
<h1>チュートリアル確認画面</h1>
	<h1>確認画面</h1>
	<h1>銘柄:<%= @company.name %></h1>
	<h1>購入株数:<%= @order.quantity %>株</h1>
	<h1>購入金額:<%= @company.value * @order.quantity %>円</h1>
	<h1>購買余力:<%= 10000000 %>円</h1>
	<h1>購入後の購買余力:<%= 10000000 - @company.value * @order.quantity %>円</h1>
	<%= form_for @order, url: trial_complete_path do |f| %>
		<%= f.hidden_field :company_id %>
		<%= f.hidden_field :quantity %>
		<%= f.hidden_field :order_value %>
		<%= f.submit "決定", class: "btn btn-large btn-primary" %>
	<% end %>
	

app/views/trial/select.html.erb
<h1>チュートリアル銘柄選択</h1>
この画面では買いたい銘柄を選択します！<br>
銘柄＝会社名のことです！<br>
株価＝１株あたりの金額です！<br>
単元株＝株の最低購入単位です。
この場合、100株以上で100の倍数でしか購入できません。<br>
購買余力=あなたの持つ現金の金額です！
<table border="1">
  <tr>
    <th>銘柄</th>
    <th>株価</th>
    <th>単元株</th>
    <th></th>
  </tr>
  <% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.value %></td>
    <td><%= company.unit %></td>
    <td><%= link_to '選択する', trial_buy_path(company) %></td>
  </tr>
  <% end %> 
</table>
<h1>購買余力:10000000円</h1>

app/views/trial/select_sell.html.erb
<h1>購買余力:<%= 10000000 - @company.value * 100 %>円</h1>
<h1>ポートフォリオ</h1>
売却画面では自分のポートフォリオが表示されるので、売りたい銘柄を選択します。<br>
ポートフォリオ=自分の持つ株などの金融商品の組み合わせ
平均取得価格=買った時点での価格の平均<br>
時価評価額=その株全ての現在価値(保有数量×現在値)<br>
評価損益=その株を買ってから現在までの収支
<table border="1">
  <tr>
    <th>銘柄</th>
    <th>保有数量</th>
    <th>平均取得価額</th>
    <th>現在値</th>
    <th>時価評価額</th>
    <th>評価損益</th>
    <th></th>
  </tr>
  <tr>
  	<td><%= @company.name %></td>
  	<td>100</td>
  	<td><%= @company.value %></td>
  	<td><%= @company.value %></td>
    <th><%= @company.value * 100 %></th>
    <th>0</th>
	<td><%= link_to 'sell', trial_sell_path %></td>
  </tr>
</table>

app/views/trial/sell.html.erb
<h2>残高:<%= 10000000 - @company.value * 100 %>円</h2>
<h2>銘柄:<%= @company.name %></h2>
<h2>現在値:<%= @company.value %>円</h2>
<h2>単元株:<%= @company.unit %>株</h2>
<h2>保有数量:100株</h2>
<%= form_for @order, url: trial_sell_confirm_path do |f| %>
     <div class="field">
     <%= f.label :quantity, "売却株数" %><br>
     <%= f.text_field :quantity %>
     <%= f.hidden_field :company_id %>
     <%= f.hidden_field :order_value %>
     <%= f.submit "確認画面へ", class: "btn btn-large btn-primary" %>
     株数に100を入力しなさい
<% end %>

app/views/trial/sell_complete.html.erb
<h1>チュートリアル売却完了</h1>
<h1><%= link_to 'トップページへ戻る', '/toppage/index' %></h1>

app/views/trial/sell_confirm.html.erb
<h1>確認画面</h1>
<h1>銘柄:<%= @company.name %></h1>
<h1>現在値:<%= @company.value %>円</h1>
<h1>売却株数:100株</h1>
<h1>売却金額:<%= 100 * @company.value %>円</h1>
<h1>売却後購買余力:10000000円</h1>
<%= form_for @order, url: trial_sell_complete_path do |f| %>
	<%= f.hidden_field :user_id %>
	<%= f.hidden_field :quantity %>
	<%= f.hidden_field :order_value %>
	<%= f.submit "決定", class: "btn btn-large btn-primary" %>
<% end %>