config/routes.rb
Kabuderby::Application.routes.draw do
  get "toppage/index"
  match'/signin', to:'sessions#new', via:'get'
  match'/signout', to:'sessions#destroy',via:'delete'
  root  'about#index'
  match '/about', to:'about#index', via:'get'
  get "/tutorial/select"
  get "/tutorial/buy/:id", to: "tutorial#buy", as: 'tutorial_buy'
  post "/tutorial/confirm/:id", to: "tutorial#confirm", as: 'tutorial_confirm'
  post "/tutorial/complete/:id", to: "tutorial#complete", as: 'tutorial_complete'
  get "toppage/mypage"
  get "/tutorial/select_sell"
  get "/tutorial/sell/:id", to: "tutorial#sell", as: 'tutorial_sell'
  post "/tutorial/sell_confirm/:id", to: "tutorial#sell_confirm", as: 'tutorial_sell_confirm'
  post "/tutorial/sell_complete/:id", to: "tutorial#sell_complete", as: 'tutorial_sell_complete'
  get "/toppage/rank"
  get "/toppage/order"
  get "/toppage/lesson"
  get "/trial/select"
  get "/trial/buy/:id", to: "trial#buy", as: 'trial_buy'
  post "/trial/confirm/:id", to: "trial#confirm", as: 'trial_confirm'
  post "/trial/complete/:id", to: "trial#complete", as: 'trial_complete'
  get "/trial/select_sell/:id", to: "trial#select_sell", as: 'trial_select_sell'
  get "/trial/sell/:id", to: "trial#sell", as: 'trial_sell'
  post "/trial/sell_confirm/:id", to: "trial#sell_confirm", as: 'trial_sell_confirm'
  post "/trial/sell_complete/:id", to: "trial#sell_complete", as: 'trial_sell_complete'
  get "/trial/order/:id", to: "trial#order", as: 'trial_order'
  get "/about/sample"



  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/controllers/toppage_controller.rb
class ToppageController < ApplicationController
  def index
  	@users = User.all
  end

  def mypage
  	@portfolios = current_user.portfolios
  end
  def rank
  	@users = User.all
  	@users.sort!{|user1, user2| user2.profit <=> user1.profit}
  end
  def order
  	@orders = current_user.orders
  end
end

app/helpers/toppage_helper.rb
module ToppageHelper
end

app/views/toppage/index.html.erb
<html>
  <head>
    <title>Hello world!</title>
  </head>
  <body>
    <h1>ユーザー名:<%= current_user.name %></h1>
    <h1>購買余力:<%= current_user.cash %>円</h1>
    <h1><%= link_to "チュートリアルへ", trial_select_path %></h1>
  	<h1><%= link_to "購入ページへ", tutorial_select_path %></h1>
  	<h1><%= link_to "売却ページへ", tutorial_select_sell_path %></h1>
  	<h1><%= link_to "ポートフォリオページへ", toppage_mypage_path %></h1>
  	<h1><%= link_to "注文照会へ", toppage_order_path %></h1>
  	<h1><%= link_to "ランキングへ", toppage_rank_path %></h1>
  	<h1><%= link_to "説明ページへ", toppage_lesson_path %></h1>
  </body>
</html>

app/views/toppage/lesson.html.erb
<h1>レッスンページ</h1>

app/views/toppage/mypage.html.erb
<h1>ポートフォリオ</h1>
<h1>ユーザー名:<%= current_user.name %></h1>

<h1>購買余力:<%=  current_user.cash %>円</h1>
<h1>株の時価評価額合計:<%= current_user.total_value %>円</h1>
<h1>資産総額:<%=  current_user.cash + current_user.total_value %>円</h1>
<h1>通算損益:<%=  current_user.cash + current_user.total_value - 10000000 %>円</h1>
<br>
<h1>持ち株一覧</h1>
<table border="1">
  <tr>
    <th>会社名</th>
    <th>保有数量</th>
    <th>平均取得価額</th>
    <th>現在値</th>
    <th>時価評価額</th>
    <th>評価損益</th>
  </tr>
  <% @portfolios.each do |portfolio| %>
  <tr>
    <td><%= portfolio.company.name %></td>
    <td><%= portfolio.quantity %></td>
    <td><%= portfolio.average %></td>
    <td><%= portfolio.company.value %></td>
    <th><%= portfolio.company.value * portfolio.quantity %></th>
    <th><%= portfolio.company.value * portfolio.quantity - portfolio.average * portfolio.quantity  %>(<%= number_to_percentage(portfolio.company.value.quo(portfolio.average) * 100 - 100) %>)</th>
  </tr>
  <% end %> 
</table>

<h1><%= link_to 'トップページへ', '/toppage/index' %></h1>

app/views/toppage/order.html.erb
<h1>注文一覧</h1>
<table border="1">
  <tr>
    <th>銘柄</th>
    <th>売/買</th>
    <th>数量</th>
    <th>価格</th>
    <th>売買金額</th>
    <th>約定日時</th>   
  </tr>
  <% @orders.each do |order| %>
  <tr>
  	<td><%= order.company.name %></td>
    <td><%= order.status %></td>
    <td><%= order.quantity %></td>
    <td><%= order.order_value %></td>
    <td><%= order.quantity * order.order_value %></td>
    <td><%= order.created_at %></td>
  </tr>
  <% end %>
</table>
<h1><%= link_to 'トップページへ', '/toppage/index' %></h1>

app/views/toppage/rank.html.erb
<h1>ランキング</h1>
<h1>ユーザー名:<%= current_user.name %></h1>
<table border="1">
  <tr>
    <th>順位</th>
    <th>ユーザー名</th>
    <th>損益</th>   
  </tr>
  <% @users.each_with_index do |user,i| %>
  <tr>
    <td><%= i + 1 %></td>
    <td><%= user.name %></td>
    <td><%= user.cash + user.total_value - 10000000 %></td>
  </tr>
  <% end %>
</table>
<h1><%= link_to 'トップページへ', '/toppage/index' %></h1>

app/views/toppage/tutorial.html.erb
<h1>チュートリアル</h1>