config/routes.rb
Kabuderby::Application.routes.draw do
  get "toppage/index"
  match'/signin', to:'sessions#new', via:'get'
  match'/signout', to:'sessions#destroy',via:'delete'
  root  'about#index'
  match '/about', to:'about#index', via:'get'
  get "/tutorial/select"
  get "/tutorial/buy/:id", to: "tutorial#buy", as: 'tutorial_buy'
  post "/tutorial/confirm/:id", to: "tutorial#confirm", as: 'tutorial_confirm'
  post "/tutorial/complete/:id", to: "tutorial#complete", as: 'tutorial_complete'
  get "toppage/mypage"
  get "/tutorial/select_sell"
  get "/tutorial/sell/:id", to: "tutorial#sell", as: 'tutorial_sell'
  post "/tutorial/sell_confirm/:id", to: "tutorial#sell_confirm", as: 'tutorial_sell_confirm'
  post "/tutorial/sell_complete/:id", to: "tutorial#sell_complete", as: 'tutorial_sell_complete'
  get "/toppage/rank"
  get "/toppage/order"
  get "/toppage/lesson"
  get "/trial/select"
  get "/trial/buy/:id", to: "trial#buy", as: 'trial_buy'
  post "/trial/confirm/:id", to: "trial#confirm", as: 'trial_confirm'
  post "/trial/complete/:id", to: "trial#complete", as: 'trial_complete'
  get "/trial/select_sell/:id", to: "trial#select_sell", as: 'trial_select_sell'
  get "/trial/sell/:id", to: "trial#sell", as: 'trial_sell'
  post "/trial/sell_confirm/:id", to: "trial#sell_confirm", as: 'trial_sell_confirm'
  post "/trial/sell_complete/:id", to: "trial#sell_complete", as: 'trial_sell_complete'
  get "/trial/order/:id", to: "trial#order", as: 'trial_order'
  get "/about/sample"



  resources :users
  resources :sessions, only: [:new, :create, :destroy]
end

app/controllers/tutorial_controller.rb
class TutorialController < ApplicationController
	before_action :set_company, only: [:buy, :confirm, :complete, :sell, :sell_complete]
	before_action :set_portfolio, only: [:confirm, :sell, :sell_confirm, :sell_complete]

	def select
		@companies = Company.all
	end

	def buy
		@order = Order.new(company_id: params[:id], order_value: @company.value)
		@portfolio = Portfolio.new(company_id: params[:id], )
	end

	def confirm
		@portfolio = Portfolio.find_by(company_id: params[:id])
		@order = Order.new(company_id: params[:id], order_value: @company.value, quantity: params[:order][:quantity] )
		if params[:order][:quantity].to_i % 100 != 0
			@error_message = 'error'
			render 'buy'
		end
	end

	def complete
		@order = Order.new(user_id: current_user.id, company_id: params[:id], quantity: params[:order][:quantity], order_value: params[:order][:order_value])
		@order.status = '買'
		@order.save
		@cash = current_user.cash - @order.order_value * @order.quantity
		current_user.cash = @cash
		current_user.save
		user = User.find_by(id: current_user.id)
		user.cash - @company.value * @order.quantity
		if user.save
			logger.debug('@@@@@@')
		else
			logger.debug(user.inspect)
		end
		if ! Portfolio.find_by(company_id: params[:id])
			portfolio = Portfolio.new(company_id: params[:id], user_id: current_user.id, quantity: params[:order][:quantity], average: params[:order][:order_value], unit: params[:order][:unit])
		else
			portfolio = Portfolio.find_by(company_id: params[:id]) 
			portfolio.quantity = portfolio.quantity + @order.quantity
		end
		portfolio.save
	end

	def select_sell
		@portfolios = current_user.portfolios
	end
	def sell
		@order = Order.new(company_id: params[:id], order_value: @company.value)
	end

	def sell_confirm
		@order = current_user.orders.build(order_params)
		
		#@portfolio = Portfolio.new(company_id: params[:id] quantity:)
		
	end

	def sell_complete
		@order = Order.new(user_id: current_user.id, company_id: params[:id], quantity: params[:order][:quantity], order_value: params[:order][:order_value])
		@order.status = '売'
		@order.save

		user = User.find_by(id: current_user.id)
		user.cash = user.cash + @order.order_value * @order.quantity
		if user.save
			logger.debug('@@@@@@')
		else
			logger.debug(user.inspect)
		end
		@portfolio = Portfolio.new(company_id: params[:id], user_id: current_user.id)
		portfolio = Portfolio.find_by(company_id: params[:id])
		portfolio.quantity = portfolio.quantity - @order.quantity
		portfolio.save

		#portfolio = Portfolio.find_by(company_id: params[:id])
		#portfolio.quantity = portfolio.quantity - @order.quantity
		#if portfolio.save
		#	logger.debug('@@@@@@')
		#else
		#	logger.debug(portfolio.inspect)
		#end
	end

	private
    # Use callbacks to share common setup or constraints between actions.

    def set_company 
      #params[id]に/users/数でとってきた値を入れている
      @company = Company.find(params[:id])
    end

    def tutorial_params
      params.require(:companies).permit(:name, :value, :unit)
    end
    
    def order_params
    	params.require(:order).permit(:quantity, :company_id, :order_value)
    end
    def set_portfolio
    	@portfolio = Portfolio.find_by(company_id: params[:id])
    end
   

end

app/helpers/tutorial_helper.rb
module TutorialHelper
end

app/views/tutorial/buy.html.erb
<% if @error_message %>
	<div class="alert alert-warning"><%= @error_message %></div>
<% end %>

<h1>
購入画面
</h1>
<h2>購買余力:<%= current_user.cash %>円</h2>
<h2>銘柄: <%= @company.name %></h2>
<h2>現在値:  <%= @company.value %>円</h2>
<h2>単元株: <%= @company.unit %>株</h2>
<%= form_for @order, url: tutorial_confirm_path do |f| %>
    <div class="field">
    <%= f.label :quantity, "購入株数" %><br>
    <%= f.text_field :quantity %>
    <%= f.hidden_field :company_id %>
    <%= f.hidden_field :order_value %>
    </div>
    <%= f.submit "確認画面へ", class: "btn btn-large btn-primary" %>
<% end %>
<h1><%= link_to 'トップページへ戻る', '/toppage/index' %></h1>

app/views/tutorial/complete.html.erb
<h1>購入完了</h1>
<h1><%= link_to 'トップページへ', '/toppage/index' %></h1>

app/views/tutorial/confirm.html.erb
<% if @company.value * @order.quantity < current_user.cash && (current_user.cash + current_user.total_value) > (@company.value * @order.quantity) * 10 + (@portfolio.quantity * @company.value) * 10  then %>
	<h1>確認画面</h1>
	<h1>銘柄:<%= @company.name %></h1>
	<h1>購入株数:<%= @order.quantity %>株</h1>
	<h1>購入金額:<%= @company.value * @order.quantity %>円</h1>
	<h1>購入後の購買余力:<%= current_user.cash - @company.value * @order.quantity %>円</h1>
	<%= form_for @order, url: {controller: 'tutorial', action: 'complete', id: @order.company_id} do |f| %>
		<%= f.hidden_field :company_id %>
		<%= f.hidden_field :user_id %>
		<%= f.hidden_field :quantity %>
		<%= f.hidden_field :order_value %>
		<%= f.submit "決定", class: "btn btn-large btn-primary" %>
	<% end %>
	<h1><%= link_to 'トップページへ戻る', '/toppage/index' %></h1>
<% else %>
	<h1>購入余力が不足しています</h1>
	<h1><%= link_to '注文画面へ', '/tutorial/select' %></h1>	
<% end %>

app/views/tutorial/select.html.erb
<h1>銘柄選択</h1>
<table border="1">
  <tr>
    <th>銘柄</th>
    <th>株価</th>
    <th>単元株</th>
    <th></th>
  </tr>
  <% @companies.each do |company| %>
  <tr>
    <td><%= company.name %></td>
    <td><%= company.value %></td>
    <td><%= company.unit %></td>
    <td><%= link_to 'buy', tutorial_buy_path(company) %></td>
  </tr>
  <% end %> 
</table>
<h1><%= link_to 'トップページへ戻る', '/toppage/index' %></h1>

app/views/tutorial/select_sell.html.erb
<h1>持ち株一覧</h1>
<table border="1">
  <tr>
    <th>会社名</th>
    <th>保有数量</th>
    <th>平均取得価額</th>
    <th>現在値</th>
    <th>時価評価額</th>
    <th>評価損益</th>
    <th></th>
  </tr>
  <% @portfolios.each do |portfolio| %>
  <tr>
  	<td><%= portfolio.company.name %></td>
  	<td><%= portfolio.quantity %></td>
  	<td><%= portfolio.average %></td>
  	<td><%= portfolio.company.value %></td>
    <th><%= portfolio.company.value * portfolio.quantity %></th>
    <th><%= portfolio.average * portfolio.quantity - portfolio.company.value * portfolio.quantity %>(<%= number_to_percentage(portfolio.average .quo(portfolio.company.value) * 100 - 100) %>)</th>
	<td><%= link_to 'sell', tutorial_sell_path(portfolio.company_id) %></td>
  </tr>
  <% end %> 
</table>
<h1><%= link_to 'トップページへ戻る', '/toppage/index' %></h1>

app/views/tutorial/sell.html.erb
<h2>残高:<%= current_user.cash %>円</h2>
<h2>銘柄:<%= @portfolio.company.name %></h2>
<h2>現在値:<%= @portfolio.company.value %>円</h2>
<h2>単元株:<%= @portfolio.company.unit %>株</h2>
<h2>保有数量:<%= @portfolio.quantity %>株</h2>
<%= form_for @order, url: tutorial_sell_confirm_path do |f| %>
     <div class="field">
     <%= f.label :quantity, "売却株数" %><br>
     <%= f.text_field :quantity %>
     <%= f.hidden_field :company_id %>
     <%= f.hidden_field :order_value %>
     <%= f.submit "確認画面へ", class: "btn btn-large btn-primary" %>
<% end %>
<h1><%= link_to 'トップページへ戻る', '/toppage/index' %></h1>

app/views/tutorial/sell_complete.html.erb
<h1>売却完了</h1>
<h1><%= link_to 'トップページへ', '/toppage/index' %></h1>

app/views/tutorial/sell_confirm.html.erb
<h1>確認画面</h1>

<% if @order.quantity <= @portfolio.quantity then %>
	<h1>銘柄:<%= @portfolio.company.name %></h1>
	<h1>現在値:<%= @portfolio.company.value %>円</h1>
	<h1>売却株数:<%= @order.quantity %>株</h1>
	<h1>売却金額:<%= @order.quantity * @portfolio.company.value %>円</h1>
	<h1>売却後の購買余力:<%= @order.quantity * @portfolio.company.value + current_user.cash %>円</h1>
	<%= form_for @order, url: tutorial_sell_complete_path do |f| %>
		<%= f.hidden_field :user_id %>
		<%= f.hidden_field :quantity %>
		<%= f.hidden_field :order_value %>
		<%= f.hidden_field :quantity %>
		<%= f.submit "決定", class: "btn btn-large btn-primary" %>
	<% end %>
	<h1><%= link_to 'トップページへ戻る', '/toppage/index' %></h1>
<% else  %>
	<h1>持ち株数が不足しています</h1>
	<h1><%= link_to '注文画面へ', '/tutorial/select_sell' %></h1>
<% end %>  